default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: snapgraph_development
test:
  <<: *default
  database: snapgraph_test

production:
  <<: *default
  database: snapgraph_production
  username: snapgraph
  password: <%= ENV['SNAPGRAPH_DATABASE_PASSWORD'] %>
